#!/usr/bin/env bash

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
NC="\033[0m"
INFO="[INFO]:"
ERR="${RED}ERROR${NC} :"

CONFIG_PATH="$HOME/.config"

check_if_dirs_exist() {
  local dirs=$1
  for dir in $dirs; do
    if [ ! -d "$dir" ]; then
      fatal "Directory '$dir' does not exist."
    else
      msg "found directory '$dir'"
    fi
  done
}

msg() {
  echo -e "${INFO} $1"
}

err_msg() {
  echo -e "${ERR} $1"
}

fatal() {
  err_msg "$1" >&2
  exit 1
}

bin_exists() {
  local package=$1

  if ! command -v "$package" &>/dev/null; then
    return 1
  else
    return 0
  fi

}

install_pkgs_apt() {
  local package=$1
  if ! apt install -y "$package" &>/dev/null; then
    fatal "Failed to install $package"
  fi
}

install_dependencies() {
  local package_map
  declare -A package_map=(
    ["neovim"]="nvim"
    ["git"]="git"
    ["wget"]="wget"
    ["tmux"]="tmux"
    ["zsh"]="zsh"
    ["clang"]="clang"
    ["shellcheck"]="shellcheck"
    ["lua-language-server"]="lua-language-server"
    ["stylua"]="stylua"
    ["shfmt"]="shfmt"
    ["fzf"]="fzf"
    ["ripgrep"]="rg"
    ["rust"]="rustc"
    ["rust-analyzer"]="rust-analyzer"
    ["python3"]="python3"
    ["python-pip"]="pip"
    ["nodejs"]="node"
    ["cmake"]="cmake"
    ["make"]="make"
  )

  local packages_bin=("${package_map[@]}")

  for pkg_bin in "${packages_bin[@]}"; do
    for pkg in "${!package_map[@]}"; do

      if [ "${package_map[$pkg]}" == "$pkg_bin" ]; then
        if ! bin_exists "$pkg_bin"; then
          msg "Installing $pkg"
          prev=$SECONDS

          install_pkgs_apt "$pkg"

          took=$((SECONDS - prev))
          msg "took ${took}s"

        else
          msg "$pkg is already installed, skipping..."
        fi
      fi

    done
  done

}

msg_head() {
  echo -e "## $1 ##"
}

set_default_shell() {
  if [[ $(basename "$SHELL") != "zsh" ]]; then
    chsh -s "zsh" || err_msg "could not set zsh as default shell. set it yourself with 'chsh -s zsh'."
  fi

}

setup_termux_theme_and_font() {
  cp ./termux/* "$HOME/.termux/" || err_msg "Could not copy the './termux' dir."

}

setup_zsh() {

  local zsh_fp="./shell/zshrc"
  local p10k_fp="./shell/p10k.zsh"
  local startup_dp="./shell/startup-files/"

  cp -r "$zsh_fp" "$HOME/.zshrc" || err_msg "Could not copy '$zsh_fp'"
  cp -r "$p10k_fp" "$HOME/.p10k.zsh" || err_msg "Could not copy '$p10k_fp'"
  cp -r "$startup_dp" "$HOME/.startup-files" || err_msg "Could not copy '$startup_dp'"

}

setup_nvim_tmux() {

  local nvim_src_path="./nvim"
  local nvim_dest_path="$CONFIG_PATH/nvim"

  if [[ -d "$nvim_dest_path" ]]; then
    local mid
    mid="$(date +%m-%M-%S)"

    local backup_path="$CONFIG_PATH/nvim.$mid.backup"
    msg "'$nvim_dest_path' already exists creating backup '$backup_path'"

    mv "$nvim_dest_path" "$backup_path" || fatal "Could not create backup."
    cp -r "$nvim_src_path" "$nvim_dest_path" || err_msg "Could not copy '$nvim_src_path'"
  else
    cp -r "$nvim_src_path" "$nvim_dest_path" || err_msg "Could not copy '$nvim_src_path'"
  fi

  local tmux_src_path="./tmux"
  local tmux_dest_path="$CONFIG_PATH/tmux"

  if [[ -d "$tmux_dest_path" ]]; then
    local mid
    mid="$(date +%m-%M-%S)"

    local backup_path="$CONFIG_PATH/tmux.$mid.backup"
    msg "'$tmux_dest_path' already exists creating backup '$backup_path'"

    mv "$tmux_dest_path" "$backup_path" || fatal "Could not create backup."
    cp -r "$tmux_src_path" "$tmux_dest_path" || err_msg "Could not copy '$tmux_src_path'"
  else
    cp -r "$tmux_src_path" "$tmux_dest_path" || err_msg "Could not copy '$tmux_src_path'"
  fi

}

create_imp_dirs() {
  local termux_dir="$HOME/.termux/"
  local config_dir="$HOME/.config/"

  mkdir "$termux_dir"
  mkdir "$config_dir"
}

exit_msg() {
  echo
  echo -e "=====Setup complete===="
  echo -e "- Please kill termux withcommand: ${GREEN}pkill -f com.termux${NC}"
  echo -e "- Open termux again and start neovim(nvim)"
  echo -e "${YELLOW}NOTE${NC}: please wait some time for all plugins to finish downloading after starting neovim."
}

setup_scripts() {
  cp -r "./scripts/" "$HOME/.scripts" || err_msg "Could not copy scripts"
}

main() {
  msg_head "Checking if required directories exist"

  local dirs=(nvim scripts shell tmux)
  check_if_dirs_exist "${dirs[*]}"

  create_imp_dirs &>/dev/null

  msg_head "Installing dependencies"
  install_dependencies

  msg_head "Setting zsh as default shell"
  set_default_shell

  msg_head "Copying p10k and zsh theme."
  setup_zsh

  msg_head "Copying termux font and themes"
  setup_termux_theme_and_font

  msg_head "Setting up neovim and tmux"
  setup_nvim_tmux

  msg_head "Copying scripts"
  setup_scripts
  exit_msg
}

main "$@"
