#!/data/data/com.termux/files/usr/bin/env sh
# ----List current tmux-sessions in a new skim window-----------

if [ -z $TMUX ]; then
  exit 1
fi

app=$(tx_launch -ls | fzf --header="Apps" --margin 15% --bind alt-m:accept,alt-e:abort)
tx_launch -a system -r "$app"
