#!/data/data/com.termux/files/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "Error: No project name provided"
  echo "Usage: $0 <project_name>"
  exit 1
fi

project_name="$1"

set -xe

mkdir "$project_name"
cd "$project_name" || exit
mkdir "css"
mkdir "script"
mkdir "assets"
touch "assets/foo.png"

cat >index.html <<'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Cool Project</title>
    <link href="css/style.css" rel="stylesheet" />
    <script src="script/index.js" type="module" defer></script>
  </head>
  <body>
    <h1>Hello,World</h1>
  </body>
</html>
EOF

cat >css/style.css <<'EOF'
*,
::after,
::before {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
EOF

cat >script/common.js <<'EOF'

export function println(fmt) {
  fmt === undefined || fmt === null ? console.log() : console.log(fmt);
}

export function pprintln(fmt, indent = 2) {
  fmt === undefined || fmt === null
    ? console.log()
    : console.log(JSON.stringify(fmt, null, indent));
}

export function throwError(errmsg = "Something went wrong") {
  throw `Error: '${errmsg}'`;
}
EOF

cat >script/index.js <<'EOF'
import { println } from "./common.js";

println("Hello,World");
EOF

set +xe
echo "------------------"
node script/index.js

echo "------------------"
